### ISSUE TITLE
Error in windows

### ISSUE THREAD

**Issue by lowburger** [jaspersiebring/libretro_finder#11]
Hi, you may advice how I can use your program? I try in windows standalone and python and receive that error in both. Thx!

![err](https://github.com/jaspersiebring/libretro_finder/assets/76657642/1139c070-bde8-467b-80c4-7fa22ae5aa56)

**Comment by jaspersiebring** [comment]
Sure! Can you dump your exact input here?

**Comment by lowburger** [comment]
The picture show log that appear when open standalone version in GUI mode.

**Comment by lowburger** [comment]
With python version anything enter give same result for me:
```
C:\Users\low>libretro_finder "C:\Users\low\Desktop\system" "C:\Users\low\Desktop\out"
Traceback (most recent call last):
  File "c:\users\low\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\low\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\low\AppData\Local\Programs\Python\Python38\Scripts\libretro_finder.exe\__main__.py", line 4, in <module>
  File "c:\users\low\appdata\local\programs\python\python38\lib\site-packages\libretro_finder\main.py", line 6, in <module>
    from config import SYSTEMS as system_df
  File "c:\users\low\appdata\local\programs\python\python38\lib\site-packages\config\__init__.py", line 52, in <module>

    RETROARCH_PATH = find_retroarch()
  File "c:\users\low\appdata\local\programs\python\python38\lib\site-packages\libretro_finder\utils.py", line 117, in find_retroarch
    drives = [
  File "c:\users\low\appdata\local\programs\python\python38\lib\site-packages\libretro_finder\utils.py", line 120, in <listcomp>
    if pathlib.Path(f"{drive}:").exists()
  File "c:\users\low\appdata\local\programs\python\python38\lib\pathlib.py", line 1407, in exists
    self.stat()
  File "c:\users\low\appdata\local\programs\python\python38\lib\pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
OSError: [WinError 87] The parameter is incorrect: 'D:'
```

**Comment by jaspersiebring** [comment]
I have not been able to reproduce this error on Windows, Linux or MacOS. Can you check if the issue still persists for the 0.3.0 release (both standalone and through pip)?

**Comment by lowburger** [comment]
I test with 0.3.1 both version and no change in error. Maybe it can be Win 7 issue?
